### ISSUE TITLE
StackFrame changes has broken other components

### ISSUE THREAD

**Issue by krassx** [stacktracejs/stackframe#10]
As you transitioned to using object as the single parameter upon creation, 'error-stack-parser' now always create empty 'StackFrame' objects. It happens because parser still passes all the parameters as arguments to the StackFrame constructor. Seems like event last versions of parser are vulnerable to this issue.

For now, I patched my local StackFrame constructor like that:

```
if (functionName instanceof Object) {
            var obj = functionName;
            var props = booleanProps.concat(numericProps.concat(stringProps.concat(arrayProps)));
            for (var i = 0; i < props.length; i++) {
                if (obj.hasOwnProperty(props[i]) && obj[props[i]] !== undefined) {
                    this['set' + _capitalize(props[i])](obj[props[i]]);
                }
            }
        } else {
            if (functionName !== undefined) {
                this.setFunctionName(functionName);
            }
            if (args !== undefined) {
                this.setArgs(args);
            }
            if (fileName !== undefined) {
                this.setFileName(fileName);
            }
            if (lineNumber !== undefined) {
                this.setLineNumber(lineNumber);
            }
            if (columnNumber !== undefined) {
                this.setColumnNumber(columnNumber);
            }
            if (source !== undefined) {
                this.setSource(source);
            }
        }
```

It's a dirty hack, but it works. Please, fix all other parts as currently it is not functional.

**Comment by eriwen** [comment]
I'm a little puzzled. `error-stack-parser` does not depend on `stackframe` v1.0 yet (though there is a PR). There are versions of other libraries that do depend on stackframe v1.0, however. Perhaps there is a dependency conflict?

Can you provide us with details about your project structure how you're declaring these dependencies, your environment and your goals?

**Comment by TehBigA** [comment]
I'm guessing he just pulled the latest file from the source browser like I just did. I noticed certain libraries don't support it yet like the error parser. Since my project doesn't have a dependency manager yet I ran into this.

**Comment by eriwen** [comment]
stacktrace-gps v3.0 and error-stack-parser v2.0 have been released which use the new Constructor. There's probably a way to provide backwards compatibility for non-strict environments, but I'll consider that a separate issue.
