### ISSUE TITLE
Any reason for choosing Unlicense over MIT?

### ISSUE THREAD

**Issue by paazmaya** [stacktracejs/stackframe#13]
I am just wondering what might be the reason of choosing Unlicense, in favour for example of MIT?

MIT would be clearer in the lawyers eyes, and even if the license would need to be changed later in to something else, the versions published with MIT are still valid as MIT.
This would not seem to be the case with Unlicense.

**Comment by oliversalzburg** [comment]
**Why Use the Unlicense?** is the title of the second paragraph on http://unlicense.org/ ;D

Public domain is also pretty simple.

**Comment by paazmaya** [comment]
Thank you for the answer
