### ISSUE TITLE
toString does not match V8 stack trace format

### ISSUE THREAD

**Issue by niftylettuce** [stacktracejs/stackframe#22]
Could we modify `toString` so that it closely matches https://v8.dev/docs/stack-trace-api#appendix%3A-stack-trace-format instead of current format?

Calling `Error.prepareStackTrace(err, stackframes)` does not give proper output.

**Comment by niftylettuce** [comment]
Here is how Node prepares it:

<https://github.com/nodejs/node/blob/b6bfc193788b1838bee73d584fe089e1104b9f88/src/node_errors.cc#L142-L175>

**Comment by eriwen** [comment]
This is fixed by #23. Thanks @niftylettuce!
