### ISSUE TITLE
Can't pull 1.1.1 from NPM

### ISSUE THREAD

**Issue by stevoPerisic** [stacktracejs/stackframe#32]
npm install fails with when trying to install cucumber js with is dependent on this package

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for stackframe@^1.1.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'stack-generator'
npm ERR! notarget
```

**Comment by eriwen** [comment]
@stevoPerisic It should be there. Here's what I see at https://www.npmjs.com/package/stackframe:

<img width="1168" alt="Screenshot 2020-01-06 09 19 08" src="https://user-images.githubusercontent.com/51534/71831239-b5507300-3065-11ea-9e22-2d3a440ac802.png">

Note that my other libraries are resolving it. What do you see now?

**Comment by stevoPerisic** [comment]
I am trying to run the install behind a corp proxy, perhaps there is an issue there. Closing for now, I appreciate the quick response!
