### ISSUE TITLE
TypeError: StackFrame is not a constructor

### ISSUE THREAD

**Issue by delbug** [stacktracejs/stackframe#52]
TypeError: StackFrame is not a constructor

**Comment by delbug** [comment]
I'm so unlucky. I have to release the official environment today, but I can't

**Comment by delbug** [comment]
I'm so unlucky. Today, the official environment will be released. Because this package reports an error, it can't be released. Can the author fix the problem?

**Comment by eriwen** [comment]
I've released stackframe v1.3.4 to address this issue. Please update and add a comment here if it doesn't work for you.

**Comment by zksfyz** [comment]
@eriwen  Thanks

**Comment by HTGH** [comment]
> I've released stackframe v1.3.4 to address this issue. Please update and add a comment here if it doesn't work for you.

怎么更新到1.3.4啊？我这里最高1.3.2

**Comment by fxzer** [comment]
npm run build就报这个错误,请问怎么解决
